In [5]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [7]:
steps = [('StandardScaler', StandardScaler()),
         ('classifier', LogisticRegression())]

In [8]:
steps

[('StandardScaler', StandardScaler()), ('classifier', LogisticRegression())]

In [9]:
pipe = Pipeline(steps)

In [10]:
pipe

Pipeline(steps=[('StandardScaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [17]:
Pipeline
[('StandardScaler', StandardScaler()), ('classifier', LogisticRegression())]

[('StandardScaler', StandardScaler()), ('classifier', LogisticRegression())]

In [21]:
from sklearn.model_selection import train_test_split
X,y=make_classification(n_samples=1000)

In [22]:
X.shape

(1000, 20)

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [25]:
X_train

array([[-0.00501743,  1.6804648 ,  1.23566377, ...,  0.80950395,
         0.81609547,  0.9557488 ],
       [-0.9939294 ,  1.57432142,  1.31193453, ...,  1.29354373,
         0.32445776,  1.04064021],
       [-0.33293037, -0.50276427,  0.8927279 , ...,  0.59802833,
        -0.50880518,  0.53088886],
       ...,
       [-0.28813571,  0.90886872, -1.21018831, ..., -2.19516883,
         2.06390664,  0.14583673],
       [ 2.36568931,  1.89860604,  0.92062115, ..., -1.0917968 ,
        -0.89745766,  1.64551638],
       [-0.11882062, -0.27613424,  0.17407502, ..., -0.54594673,
        -0.20835285, -2.36417194]])

In [27]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('StandardScaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [30]:
y_pred=pipe.predict(X_test)

In [31]:
y_pred

array([0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1])

In [35]:
from sklearn.decomposition import PCA
from sklearn.svm import SVC

In [37]:
steps = [('scaler', StandardScaler()),
    ('pca', PCA(n_components=2)),
    ('SVC', SVC())]

In [38]:
pipe2 = Pipeline(steps)

In [39]:
pipe2.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()), ('pca', PCA(n_components=2)),
                ('SVC', SVC())])

In [40]:
y_pred_svc = pipe2.predict(X_test)
y_pred_svc

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1])

In [44]:
from sklearn.impute import SimpleImputer

In [45]:
import numpy as np
numeric_processor = Pipeline(steps=[
    ('imputation_mean', SimpleImputer(missing_values=np.nan,strategy='mean')),
    ('scaler', StandardScaler())
])

In [47]:
numeric_processor

Pipeline(steps=[('imputation_mean', SimpleImputer()),
                ('scaler', StandardScaler())])

In [51]:
from sklearn.preprocessing import OneHotEncoder
categorical_processor = Pipeline(steps=[{"imputation_constant", SimpleImputer(fill_value='missing',strategy='constant')},
                                        ('onehot', OneHotEncoder(handle_unknown='ignore'))])

In [52]:
categorical_processor

Pipeline(steps=[{SimpleImputer(fill_value='missing', strategy='constant'),
                 'imputation_constant'},
                ('onehot', OneHotEncoder(handle_unknown='ignore'))])

In [53]:
from sklearn.compose import ColumnTransformer

In [54]:
preprocessor = ColumnTransformer(
    transformers=[[("categorical", categorical_processor, ['gender', 'City']),
                   ("numerical", numeric_processor, ['Age', 'Height'])
                   ]])

In [56]:
from sklearn.pipeline import make_pipeline

In [57]:
pipe = make_pipeline(preprocessor, LogisticRegression())

In [58]:
pipe

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[[('categorical',
                                                   Pipeline(steps=[{SimpleImputer(fill_value='missing',
                                                                                  strategy='constant'),
                                                                    'imputation_constant'},
                                                                   ('onehot',
                                                                    OneHotEncoder(handle_unknown='ignore'))]),
                                                   ['gender', 'City']),
                                                  ('numerical',
                                                   Pipeline(steps=[('imputation_mean',
                                                                    SimpleImputer()),
                                                                   ('scaler',
                                                                    StandardScaler())]),
                                                   ['Age', 'Height'])]])),
                ('logisticregression', LogisticRegression())])